[package]
name = "text_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.0.2"
crossbeam-channel = "0.5.7"
libc = "0.2.140"
ropey = "1.6.0"
